---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-azure-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      serviceAccountRef:
        name: sa-workload-identity
        namespace: external-secrets
      vaultUrl: https://kv-crazyninja-ri7f.vault.azure.net
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: fc9dbe57-8df5-4691-8953-751b9ff8fe92
    azure.workload.identity/tenant-id: c7bcbdd7-a080-4551-9f40-bdfc308ec2f2
  name: sa-workload-identity
  namespace: external-secrets

